// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTask = "task"

// Task 任务表
type Task struct {
	TaskID    int64     `gorm:"column:task_id;primaryKey;autoIncrement:true;comment:任务ID（自增主键）" json:"task_id"`      // 任务ID（自增主键）
	UserID    int64     `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                 // 用户ID
	Title     string    `gorm:"column:title;not null;comment:任务标题" json:"title"`                                     // 任务标题
	Status    int32     `gorm:"column:status;not null;comment:任务状态（0:未开始, 1:进行中, 2:已完成）" json:"status"`              // 任务状态（0:未开始, 1:进行中, 2:已完成）
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
