// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: task.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=TaskId,proto3" json:"TaskId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskModel) Reset() {
	*x = TaskModel{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskModel) ProtoMessage() {}

func (x *TaskModel) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskModel.ProtoReflect.Descriptor instead.
func (*TaskModel) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskModel) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskModel) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TaskModel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskModel) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=TaskId,proto3" json:"TaskId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type TasksDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskDetail    []*TaskModel           `protobuf:"bytes,1,rep,name=TaskDetail,proto3" json:"TaskDetail,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TasksDetailResponse) Reset() {
	*x = TasksDetailResponse{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksDetailResponse) ProtoMessage() {}

func (x *TasksDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksDetailResponse.ProtoReflect.Descriptor instead.
func (*TasksDetailResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *TasksDetailResponse) GetTaskDetail() []*TaskModel {
	if x != nil {
		return x.TaskDetail
	}
	return nil
}

func (x *TasksDetailResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type TaskCommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCommonResponse) Reset() {
	*x = TaskCommonResponse{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCommonResponse) ProtoMessage() {}

func (x *TaskCommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCommonResponse.ProtoReflect.Descriptor instead.
func (*TaskCommonResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *TaskCommonResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TaskCommonResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TaskCommonResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\"i\n" +
	"\tTaskModel\x12\x16\n" +
	"\x06TaskId\x18\x01 \x01(\x03R\x06TaskId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x14\n" +
	"\x05Title\x18\x03 \x01(\tR\x05Title\x12\x16\n" +
	"\x06Status\x18\x04 \x01(\x03R\x06Status\"S\n" +
	"\vTaskRequest\x12\x16\n" +
	"\x06TaskId\x18\x01 \x01(\x03R\x06TaskId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x14\n" +
	"\x05Title\x18\x03 \x01(\tR\x05Title\"U\n" +
	"\x13TasksDetailResponse\x12*\n" +
	"\n" +
	"TaskDetail\x18\x01 \x03(\v2\n" +
	".TaskModelR\n" +
	"TaskDetail\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\"N\n" +
	"\x12TaskCommonResponse\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x03R\x04Code\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\tR\x04Data2\xd0\x01\n" +
	"\vTaskService\x12/\n" +
	"\n" +
	"TaskCreate\x12\f.TaskRequest\x1a\x13.TaskCommonResponse\x12/\n" +
	"\n" +
	"TaskUpdate\x12\f.TaskRequest\x1a\x13.TaskCommonResponse\x12.\n" +
	"\bTaskShow\x12\f.TaskRequest\x1a\x14.TasksDetailResponse\x12/\n" +
	"\n" +
	"TaskDelete\x12\f.TaskRequest\x1a\x13.TaskCommonResponseB\aZ\x05task/b\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_task_proto_goTypes = []any{
	(*TaskModel)(nil),           // 0: TaskModel
	(*TaskRequest)(nil),         // 1: TaskRequest
	(*TasksDetailResponse)(nil), // 2: TasksDetailResponse
	(*TaskCommonResponse)(nil),  // 3: TaskCommonResponse
}
var file_task_proto_depIdxs = []int32{
	0, // 0: TasksDetailResponse.TaskDetail:type_name -> TaskModel
	1, // 1: TaskService.TaskCreate:input_type -> TaskRequest
	1, // 2: TaskService.TaskUpdate:input_type -> TaskRequest
	1, // 3: TaskService.TaskShow:input_type -> TaskRequest
	1, // 4: TaskService.TaskDelete:input_type -> TaskRequest
	3, // 5: TaskService.TaskCreate:output_type -> TaskCommonResponse
	3, // 6: TaskService.TaskUpdate:output_type -> TaskCommonResponse
	2, // 7: TaskService.TaskShow:output_type -> TasksDetailResponse
	3, // 8: TaskService.TaskDelete:output_type -> TaskCommonResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
